In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [6]:
x = df.drop('species', axis=1)
y = df['species']

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [10]:
knn.score(x_test, y_test)

0.98

In [11]:
from sklearn.svm import SVC

In [12]:
svm = SVC(gamma = 'auto') #1.0 for C=10
svm.fit(x_train, y_train)

SVC(gamma='auto')

In [13]:
svm.score(x_test, y_test)

1.0

GRID SEARCH CV

In [14]:
from sklearn.model_selection import GridSearchCV

In [15]:
classifier = GridSearchCV((svm),{
    'C':[1,10,20,30],
    'kernel':['rbf', 'linear']
}, cv=5, return_train_score=False)

In [16]:
classifier.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [17]:
classifier.cv_results_

{'mean_fit_time': array([0.00930462, 0.00777931, 0.00935745, 0.00630298, 0.0038609 ,
        0.00538206, 0.01308222, 0.00339589]),
 'std_fit_time': array([0.00370498, 0.00265318, 0.00481228, 0.00487306, 0.00067489,
        0.00219731, 0.0055622 , 0.00014266]),
 'mean_score_time': array([0.00999742, 0.00550041, 0.00631452, 0.00351624, 0.00333691,
        0.00440578, 0.00980539, 0.00309825]),
 'std_score_time': array([0.00458115, 0.00244135, 0.00260827, 0.00110032, 0.00076801,
        0.0021934 , 0.00636926, 0.00092576]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.8 , 0.85, 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 1.  , 0.95, 0.95, 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.93, 0.92, 0.93, 0.93, 0.94]),
 'std_test_score': array([0.03741657, 0.04472136, 0.07483315, 0.0509902 , 0.0678233 ,
        0.0509902 , 0.07483315, 0.05830952]),
 'rank_test_score': array([2, 1, 4, 6, 8, 6, 4, 3], dtype=int32)}

In [18]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009305,0.003705,0.009997,0.004581,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,2
1,0.007779,0.002653,0.005500,0.002441,1,linear,"{'C': 1, 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.009357,0.004812,0.006315,0.002608,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
3,0.006303,0.004873,0.003516,0.001100,10,linear,"{'C': 10, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,6
4,0.003861,0.000675,0.003337,0.000768,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,8
5,0.005382,0.002197,0.004406,0.002193,20,linear,"{'C': 20, 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,6
6,0.013082,0.005562,0.009805,0.006369,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
7,0.003396,0.000143,0.003098,0.000926,30,linear,"{'C': 30, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,3

In [19]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf             0.94
1        1       linear             0.95
2       10          rbf             0.93
3       10       linear             0.93
4       20          rbf             0.92
5       20       linear             0.93
6       30          rbf             0.93
7       30       linear             0.94

RANDOM SEARCH CV

In [20]:
from sklearn.model_selection import RandomizedSearchCV

In [21]:
random_classifier = RandomizedSearchCV((svm),{
    'C':[1,10,20,30],
    'kernel':['rbf', 'linear']
}, n_iter = 4, cv=5, return_train_score=False)

In [22]:
random_classifier.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [23]:
random_classifier.cv_results_

{'mean_fit_time': array([0.00611668, 0.00922184, 0.00939121, 0.00469146]),
 'std_fit_time': array([0.00227302, 0.00378865, 0.005466  , 0.0019704 ]),
 'mean_score_time': array([0.00343108, 0.00756283, 0.00744634, 0.00356011]),
 'std_score_time': array([0.00045358, 0.00254977, 0.00346749, 0.00109645]),
 'param_kernel': masked_array(data=['rbf', 'rbf', 'linear', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[20, 10, 20, 10],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 20},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'linear', 'C': 10}],
 'split0_test_score': array([0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.8 , 0.8 , 0.85, 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 0.95, 1.  ]),
 'split4_test_score': array([0.95, 1.  , 1.  , 0.95]),
 'mean_test_score': array([0.92, 0.93, 0.93, 0.93]),
 'std_test_score': array([0.0678233 , 0.07483315, 0.0509902 , 0.0509902 ]),
 'rank_test_score': array([4, 1, 2, 2], dtype=int32)}

In [24]:
pd.DataFrame(random_classifier.cv_results_)[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20          rbf             0.92
1       10          rbf             0.93
2       20       linear             0.93
3       10       linear             0.93