In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a', 'b', 'c']
mylist = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10, 'b':20, 'c':30}

In [ ]:
pd.Series(mylist,index = labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

Dataframes

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    "Name":["Jai", "Princi", "Gaurav", "Anuj"],
    "Age":[27, 24, 22, 32],
    "Address":["Delhi", "Kanpur", "Allahabad", "Kannauj"],
    "Qualification":["Msc", "MA", "MCA", "Phd"],
    "Salary":[65000,7000,32000,90000]
}
df1 = pd.DataFrame(data)

In [ ]:
data_list = [
    ["Jai", 27, "Delhi", "Msc", 65000],
    ["Princi", 24, "Kanpur", "MA", 7000],
    ["Gaurav", 22, "Allahabad", "MCA", 32000],
    ["Anuj",32,"Kannauj","Phd", 90000]
]
column = ["Name", "Age", "Address", "Qualification", "Salary"]
df2 = pd.DataFrame(data_list, columns = ["Name", "Age", "Address", "Qualification", "Salary"])

In [ ]:
df2

     Name  Age    Address Qualification  Salary
0     Jai   27      Delhi           Msc   65000
1  Princi   24     Kanpur            MA    7000
2  Gaurav   22  Allahabad           MCA   32000
3    Anuj   32    Kannauj           Phd   90000

In [ ]:
df2["Name"]

0       Jai
1    Princi
2    Gaurav
3      Anuj
Name: Name, dtype: object

In [ ]:
df2[["Name","Salary"]]

     Name  Salary
0     Jai   65000
1  Princi    7000
2  Gaurav   32000
3    Anuj   90000

In [ ]:
df2["Domain"]=["Education","Sales","Business","ISRO"]
df2

     Name  Age    Address Qualification  Salary     Domain
0     Jai   27      Delhi           Msc   65000  Education
1  Princi   24     Kanpur            MA    7000      Sales
2  Gaurav   22  Allahabad           MCA   32000   Business
3    Anuj   32    Kannauj           Phd   90000       ISRO

In [ ]:
#df2.drop("Address",axis=1)--->temporary drop
df2.drop("Address",axis=1,inplace=True)#permanent drop
df2

     Name  Age Qualification  Salary     Domain
0     Jai   27           Msc   65000  Education
1  Princi   24            MA    7000      Sales
2  Gaurav   22           MCA   32000   Business
3    Anuj   32           Phd   90000       ISRO

In [ ]:
df2.drop(["Age","Domain"],axis=1)

     Name Qualification  Salary
0     Jai           Msc   65000
1  Princi            MA    7000
2  Gaurav           MCA   32000
3    Anuj           Phd   90000

In [ ]:
df2.loc[[0,1]]

     Name  Age Qualification  Salary     Domain
0     Jai   27           Msc   65000  Education
1  Princi   24            MA    7000      Sales

In [ ]:
df2.iloc[3]

Name              Anuj
Age                 32
Qualification      Phd
Salary           90000
Domain            ISRO
Name: 3, dtype: object

In [ ]:
df2.loc[[0,1]][["Name","Salary"]]

     Name  Salary
0     Jai   65000
1  Princi    7000

In [ ]:
df2.loc[[2,3]][["Domain","Salary"]]

     Domain  Salary
2  Business   32000
3      ISRO   90000

In [ ]:
#age>25
df2.loc[:][df2["Age"]>25]

   Name  Age Qualification  Salary     Domain
0   Jai   27           Msc   65000  Education
3  Anuj   32           Phd   90000       ISRO

In [ ]:
df2[df2["Age"]>25]

   Name  Age Qualification  Salary     Domain
0   Jai   27           Msc   65000  Education
3  Anuj   32           Phd   90000       ISRO

In [ ]:
#age<30 and salary>50000
df2.loc[(df2["Age"]<30) & (df2["Salary"]>50000)]

  Name  Age Qualification  Salary     Domain
0  Jai   27           Msc   65000  Education

In [ ]:
df2[(df2["Age"]<30) & (df2["Salary"]>50000)]

  Name  Age Qualification  Salary     Domain
0  Jai   27           Msc   65000  Education

Missing data

In [ ]:
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [6, 7, np.nan, 9, 10],
    'C': [11, 12, 13, np.nan, 15],
    'D': [16, np.nan, 18, 19, np.nan]
}
df = pd.DataFrame(data)
df

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0   NaN
2  3   NaN  13.0  18.0
3  4   9.0   NaN  19.0
4  5  10.0  15.0   NaN

In [ ]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2  False   True  False  False
3  False  False   True  False
4  False  False  False   True

In [ ]:
df.isna().sum()

A    0
B    1
C    1
D    2
dtype: int64

In [ ]:
df.isna().any()

A    False
B     True
C     True
D     True
dtype: bool

In [ ]:
df.dropna()

   A    B     C     D
0  1  6.0  11.0  16.0

In [ ]:
df.dropna(thresh=3)#atleast 3 non-null

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0   NaN
2  3   NaN  13.0  18.0
3  4   9.0   NaN  19.0
4  5  10.0  15.0   NaN

In [ ]:
df.fillna(0)

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0   0.0
2  3   0.0  13.0  18.0
3  4   9.0   0.0  19.0
4  5  10.0  15.0   0.0

In [ ]:
values = {'A': 0, 'B': 1, 'C': 2, 'D': 3}#column wise
df.fillna(value=values)

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0   3.0
2  3   1.0  13.0  18.0
3  4   9.0   2.0  19.0
4  5  10.0  15.0   3.0

In [ ]:
df.fillna(value=df["B"].mean())

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0   8.0
2  3   8.0  13.0  18.0
3  4   9.0   8.0  19.0
4  5  10.0  15.0   8.0

Merge & Concat

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
employee = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Jane', 'Bob', 'Alice', 'Mike'],
    'department_name': ['HR', 'IT', 'Finance', 'IT', 'Sales']
})
salary = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [50000, 60000, 55000, 70000, 65000],
    'bonus': [1000, 2000, 1500, 2500, 3000]
})

In [ ]:
employee

   employee_id   name department_name
0            1   John              HR
1            2   Jane              IT
2            3    Bob         Finance
3            4  Alice              IT
4            5   Mike           Sales

In [ ]:
salary

   employee_id  salary  bonus
0            1   50000   1000
1            2   60000   2000
2            3   55000   1500
3            6   70000   2500
4            7   65000   3000

In [ ]:
#pd.merge(employee,salary) --->default
pd.merge(employee,salary,on="employee_id")

   employee_id  name department_name  salary  bonus
0            1  John              HR   50000   1000
1            2  Jane              IT   60000   2000
2            3   Bob         Finance   55000   1500

In [ ]:
pd.merge(employee,salary,on="employee_id",how="outer")

   employee_id   name department_name   salary   bonus
0            1   John              HR  50000.0  1000.0
1            2   Jane              IT  60000.0  2000.0
2            3    Bob         Finance  55000.0  1500.0
3            4  Alice              IT      NaN     NaN
4            5   Mike           Sales      NaN     NaN
5            6    NaN             NaN  70000.0  2500.0
6            7    NaN             NaN  65000.0  3000.0

In [ ]:
pd.merge(employee,salary,on="employee_id",how="left")

   employee_id   name department_name   salary   bonus
0            1   John              HR  50000.0  1000.0
1            2   Jane              IT  60000.0  2000.0
2            3    Bob         Finance  55000.0  1500.0
3            4  Alice              IT      NaN     NaN
4            5   Mike           Sales      NaN     NaN

Concat

In [ ]:
df1 = pd.DataFrame({
    "A":[1,2,3,4],
    "B":[5,6,7,8],
    "C":[9,10,11,12]
})
df2 = pd.DataFrame({
    "A":[13,14,15,16],
    "B":[17,18,19,20],
    "C":[21,22,23,24]
})
pd.concat([df1,df2])
#

    A   B   C
0   1   5   9
1   2   6  10
2   3   7  11
3   4   8  12
0  13  17  21
1  14  18  22
2  15  19  23
3  16  20  24

In [ ]:
pd.concat([df1,df2],axis=1)

   A  B   C   A   B   C
0  1  5   9  13  17  21
1  2  6  10  14  18  22
2  3  7  11  15  19  23
3  4  8  12  16  20  24

GroupBy

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S2', 'S1', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 300, 250, 350, 500, 200],
    'Quantity': [10, 20, 15, 30, 25, 35, 50, 20],
    'Date': pd.date_range(start='2026-07-26', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2026-07-26
1        A    S2    200        20 2026-07-27
2        B    S1    150        15 2026-07-28
3        B    S2    300        30 2026-07-29
4        A    S1    250        25 2026-07-30
5        B    S2    350        35 2026-07-31
6        A    S2    500        50 2026-08-01
7        B    S1    200        20 2026-08-02

In [ ]:
cat = df.groupby('Category')
for i,j in cat:
  print(i)
  print(j)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2026-07-26
1        A    S2    200        20 2026-07-27
4        A    S1    250        25 2026-07-30
6        A    S2    500        50 2026-08-01
B
  Category Store  Sales  Quantity       Date
2        B    S1    150        15 2026-07-28
3        B    S2    300        30 2026-07-29
5        B    S2    350        35 2026-07-31
7        B    S1    200        20 2026-08-02

In [ ]:
cat = df.groupby('Category')['Sales'].sum()
print(cat)

Category
A    1050
B    1000
Name: Sales, dtype: int64

In [ ]:
cat = df.groupby(['Category','Store'])['Sales'].sum()
print(cat)

Category  Store
A         S1       350
          S2       700
B         S1       350
          S2       650
Name: Sales, dtype: int64

In [ ]:
df['Sales'].agg(['sum','mean','max','min'])

sum     2050.00
mean     256.25
max      500.00
min      100.00
Name: Sales, dtype: float64

Pivot Tables

In [ ]:
import numpy as np
import pandas as pd
import random

In [ ]:
data = {
    'Date': pd.date_range(start='2026-06-26', periods=20),
    'Product': ['A','B','C','D'] * 5,
    'Region': ['East','West','North','North','South','West','East','South','West','East','North','West','East','South','West','East','South','West','East','South'],
    'Sales': np.random.randint(100,1000,20),
    'Units': np.random.randint(10,100,20),
    'Rep': ['John','Jane','Bob','Alice','Mike','Jane','Mike','Bob','Alice','John','Bob','Alice','John','Jane','Mike','Bob','Alice','John','Jane','Mike']

}
df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep Month Quarter
0  2026-06-26       A   East    870     48   John  June      Q2
1  2026-06-27       B   West    344     47   Jane  June      Q2
2  2026-06-28       C  North    762     17    Bob  June      Q2
3  2026-06-29       D  North    618     76  Alice  June      Q2
4  2026-06-30       A  South    978     82   Mike  June      Q2
5  2026-07-01       B   West    842     96   Jane  July      Q3
6  2026-07-02       C   East    186     70   Mike  July      Q3
7  2026-07-03       D  South    550     71    Bob  July      Q3
8  2026-07-04       A   West    265     21  Alice  July      Q3
9  2026-07-05       B   East    170     16   John  July      Q3
10 2026-07-06       C  North    679     81    Bob  July      Q3
11 2026-07-07       D   West    245     74  Alice  July      Q3
12 2026-07-08       A   East    195     94   John  July      Q3
13 2026-07-09       B  South    428     78   Jane  July      Q3
14 2026-07-10       C   West    264     21   Mike  July      Q3
15 2026-07-11       D   East    204     11    Bob  July      Q3
16 2026-07-12       A  South    146     75  Alice  July      Q3
17 2026-07-13       B   West    992     90   John  July      Q3
18 2026-07-14       C   East    128     68   Jane  July      Q3
19 2026-07-15       D  South    368     38   Mike  July      Q3

In [ ]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='sum')#aggfunc=mean by default

Product       A       B       C      D
Region
East     1065.0   170.0   314.0  204.0
North       NaN     NaN  1441.0  618.0
South    1124.0   428.0     NaN  918.0
West      265.0  2178.0   264.0  245.0

In [ ]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product',aggfunc='sum')
pivot2

          Sales                         Units
Product       A       B       C      D      A      B      C      D
Region
East     1065.0   170.0   314.0  204.0  142.0   16.0  138.0   11.0
North       NaN     NaN  1441.0  618.0    NaN    NaN   98.0   76.0
South    1124.0   428.0     NaN  918.0  157.0   78.0    NaN  109.0
West      265.0  2178.0   264.0  245.0   21.0  233.0   21.0   74.0

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     2  1  2  1
North    0  0  2  1
South    2  1  0  2
West     1  3  1  1

Operations

In [ ]:
df1 = {
    'Num': [1,2,3,4,5],
    'Sqaure': [1,4,9,16,25],
    'Cube': [1,8,27,64,125]
}
df1 = pd.DataFrame(df1)
df1

   Num  Sqaure  Cube
0    1       1     1
1    2       4     8
2    3       9    27
3    4      16    64
4    5      25   125

In [ ]:
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['Num', 'Sqaure', 'Cube'], dtype='object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Num     5 non-null      int64
 1   Sqaure  5 non-null      int64
 2   Cube    5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

            Num    Sqaure        Cube
count  5.000000   5.00000    5.000000
mean   3.000000  11.00000   45.000000
std    1.581139   9.66954   50.965675
min    1.000000   1.00000    1.000000
25%    2.000000   4.00000    8.000000
50%    3.000000   9.00000   27.000000
75%    4.000000  16.00000   64.000000
max    5.000000  25.00000  125.000000

In [ ]:
df1['Cube'] + 10

0     11
1     18
2     37
3     74
4    135
Name: Cube, dtype: int64

In [ ]:
def square(x):
  return x**2

In [ ]:
df1['Num'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: Num, dtype: int64

In [ ]:
df1

   Num  Sqaure  Cube    Quad
0    1       1     1       1
1   16       4     8     256
2   81       9    27    6561
3  256      16    64   65536
4  625      25   125  390625

In [ ]:
df1['Num'].apply(square) #to actually change
df1['Quad'] = df1['Num'].apply(square) #inline= true
df1

   Num  Sqaure  Cube    Quad
0    1       1     1       1
1   16       4     8     256
2   81       9    27    6561
3  256      16    64   65536
4  625      25   125  390625